AllCops:
  Exclude:
    - db/schema.rb

# Configuration parameters: AllowSafeAssignment.
Lint/AssignmentInCondition:
  Enabled: false

# Cop supports --auto-correct.
Lint/BlockAlignment:
  Enabled: true

# Configuration parameters: AlignWith, SupportedStyles.
Lint/DefEndAlignment:
  Enabled: true

# Cop supports --auto-correct.
Lint/DeprecatedClassMethods:
  Enabled: true

Lint/ParenthesesAsGroupedExpression:
  Enabled: true

Lint/ShadowingOuterLocalVariable:
  Enabled: true

# Cop supports --auto-correct.
Lint/UnusedBlockArgument:
  Enabled: true

# Cop supports --auto-correct.
Lint/UnusedMethodArgument:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

Metrics/AbcSize:
  Max: 55

# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 629

Metrics/CyclomaticComplexity:
  Max: 10

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 557

# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 294

# Configuration parameters: CountKeywordArgs.
Metrics/ParameterLists:
  Max: 6

Metrics/PerceivedComplexity:
  Max: 13

# Cop supports --auto-correct.
# Configuration parameters: EnforcedHashRocketStyle, EnforcedColonStyle, EnforcedLastArgumentHashStyle, SupportedLastArgumentHashStyles.
Style/AlignHash:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/AndOr:
  Enabled: true

Style/AsciiComments:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/BarePercentLiterals:
  Enabled: true

# Cop supports --auto-correct.
Style/Blocks:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/BracesAroundHashParameters:
  Enabled: true

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/ClassAndModuleChildren:
  Enabled: true

Style/ClassVars:
  Enabled: true

# Cop supports --auto-correct.
Style/ColonMethodCall:
  Enabled: true

# Cop supports --auto-correct.
Style/CommentIndentation:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/EachWithObject:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: AllowAdjacentOneLineDefs.
Style/EmptyLineBetweenDefs:
  Enabled: true

# Cop supports --auto-correct.
Style/EmptyLines:
  Enabled: true

# Cop supports --auto-correct.
Style/EmptyLinesAroundAccessModifier:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/EmptyLinesAroundClassBody:
  Enabled: false

# Cop supports --auto-correct.
Style/EmptyLinesAroundMethodBody:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/EmptyLinesAroundModuleBody:
  Enabled: true

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/FormatString:
  Enabled: true

# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/HashSyntax:
  Enabled: true

# Configuration parameters: MaxLineLength.
Style/IfUnlessModifier:
  Enabled: true

# Cop supports --auto-correct.
Style/IndentArray:
  Enabled: true

# Cop supports --auto-correct.
Style/IndentationConsistency:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: Width.
Style/IndentationWidth:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: SupportedStyles.
Style/LambdaCall:
  EnforcedStyle: braces

# Cop supports --auto-correct.
Style/LeadingCommentSpace:
  Enabled: true

# Cop supports --auto-correct.
Style/MethodCallParentheses:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/MethodDefParentheses:
  Enabled: true

Style/MultilineBlockChain:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/MultilineOperationIndentation:
  Enabled: true

# Cop supports --auto-correct.
Style/NegatedIf:
  Enabled: true

# Cop supports --auto-correct.
Style/NegatedWhile:
  Enabled: true

# Configuration parameters: EnforcedStyle, MinBodyLength, SupportedStyles.
Style/Next:
  Enabled: true

# Cop supports --auto-correct.
Style/NumericLiterals:
  MinDigits: 15

# Cop supports --auto-correct.
# Configuration parameters: AllowSafeAssignment.
Style/ParenthesesAroundCondition:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: PreferredDelimiters.
Style/PercentLiteralDelimiters:
  Enabled: true

# Configuration parameters: NamePrefix, NamePrefixBlacklist.
Style/PredicateName:
  Enabled: true

# Configuration parameters: SupportedStyles.
Style/RaiseArgs:
  EnforcedStyle: compact

# Cop supports --auto-correct.
# Configuration parameters: AllowMultipleReturnValues.
Style/RedundantReturn:
  Enabled: true

# Cop supports --auto-correct.
Style/RedundantSelf:
  Enabled: true

Style/RegexpLiteral:
  MaxSlashes: 0

# Cop supports --auto-correct.
# Configuration parameters: AllowAsExpressionSeparator.
Style/Semicolon:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/SignalException:
  Enabled: true

# Configuration parameters: Methods.
Style/SingleLineBlockParams:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: AllowIfMethodIsEmpty.
Style/SingleLineMethods:
  Enabled: true

# Cop supports --auto-correct.
Style/SingleSpaceBeforeFirstArg:
  Enabled: true

# Cop supports --auto-correct.
Style/SpaceAfterColon:
  Enabled: true

# Cop supports --auto-correct.
Style/SpaceAfterComma:
  Enabled: true

# Cop supports --auto-correct.
Style/SpaceAfterControlKeyword:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/SpaceAroundEqualsInParameterDefault:
  Enabled: true

# Cop supports --auto-correct.
Style/SpaceAroundOperators:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/SpaceBeforeBlockBraces:
  Enabled: true

# Cop supports --auto-correct.
Style/SpaceBeforeComma:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, EnforcedStyleForEmptyBraces, SpaceBeforeBlockParameters.
Style/SpaceInsideBlockBraces:
  Enabled: true

# Cop supports --auto-correct.
Style/SpaceInsideBrackets:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, EnforcedStyleForEmptyBraces, SupportedStyles.
Style/SpaceInsideHashLiteralBraces:
  Enabled: true

# Cop supports --auto-correct.
Style/SpaceInsideParens:
  Enabled: true

# Cop supports --auto-correct.
Style/SpecialGlobalVars:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

# Cop supports --auto-correct.
# Configuration parameters: IgnoredMethods.
Style/SymbolProc:
  Enabled: true

# Cop supports --auto-correct.
Style/Tab:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/TrailingBlankLines:
  Enabled: true

# Cop supports --auto-correct.
Style/TrailingWhitespace:
  Enabled: true

# Cop supports --auto-correct.
Style/UnneededPercentQ:
  Enabled: true

# Cop supports --auto-correct.
Style/WhileUntilDo:
  Enabled: true

# Cop supports --auto-correct.
# Configuration parameters: WordRegex.
Style/WordArray:
  MinSize: 51
